// <auto-generated />
using AgroSolutions.Property.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AgroSolutions.Property.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AgroSolutionsPropertyDbContext))]
    [Migration("20260204020147_ConfiguredCascadeInPropertyAndField")]
    partial class ConfiguredCascadeInPropertyAndField
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AgroSolutions.Property.Domain.Entities.Crop", b =>
                {
                    b.Property<int>("CropId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CropId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("CropId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Crops");

                    b.HasData(
                        new
                        {
                            CropId = 1,
                            Name = "Soja"
                        },
                        new
                        {
                            CropId = 2,
                            Name = "Milho"
                        },
                        new
                        {
                            CropId = 3,
                            Name = "Feijão"
                        },
                        new
                        {
                            CropId = 4,
                            Name = "Arroz"
                        },
                        new
                        {
                            CropId = 5,
                            Name = "Trigo"
                        },
                        new
                        {
                            CropId = 6,
                            Name = "Algodão"
                        },
                        new
                        {
                            CropId = 7,
                            Name = "Cana-de-açúcar"
                        },
                        new
                        {
                            CropId = 8,
                            Name = "Café"
                        },
                        new
                        {
                            CropId = 9,
                            Name = "Laranja"
                        },
                        new
                        {
                            CropId = 10,
                            Name = "Tomate"
                        },
                        new
                        {
                            CropId = 11,
                            Name = "Alface"
                        },
                        new
                        {
                            CropId = 12,
                            Name = "Girassol"
                        },
                        new
                        {
                            CropId = 13,
                            Name = "Aveia"
                        },
                        new
                        {
                            CropId = 14,
                            Name = "Cevada"
                        },
                        new
                        {
                            CropId = 15,
                            Name = "Batata"
                        },
                        new
                        {
                            CropId = 16,
                            Name = "Cebola"
                        },
                        new
                        {
                            CropId = 17,
                            Name = "Uva"
                        },
                        new
                        {
                            CropId = 18,
                            Name = "Pinho"
                        },
                        new
                        {
                            CropId = 19,
                            Name = "Capim"
                        },
                        new
                        {
                            CropId = 20,
                            Name = "Eucalipto"
                        });
                });

            modelBuilder.Entity("AgroSolutions.Property.Domain.Entities.Field", b =>
                {
                    b.Property<int>("FieldId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FieldId"));

                    b.Property<int>("CropId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PropertyId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAreaInHectares")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("FieldId");

                    b.HasIndex("CropId");

                    b.HasIndex("PropertyId", "Name")
                        .IsUnique();

                    b.ToTable("Fields");
                });

            modelBuilder.Entity("AgroSolutions.Property.Domain.Entities.Property", b =>
                {
                    b.Property<int>("PropertyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PropertyId"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("PropertyId");

                    b.ToTable("Properties");
                });

            modelBuilder.Entity("AgroSolutions.Property.Domain.Entities.Field", b =>
                {
                    b.HasOne("AgroSolutions.Property.Domain.Entities.Crop", "Crop")
                        .WithMany()
                        .HasForeignKey("CropId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgroSolutions.Property.Domain.Entities.Property", "Property")
                        .WithMany("Fields")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Crop");

                    b.Navigation("Property");
                });

            modelBuilder.Entity("AgroSolutions.Property.Domain.Entities.Property", b =>
                {
                    b.Navigation("Fields");
                });
#pragma warning restore 612, 618
        }
    }
}
